#!/bin/bash
#this file is not finished yet
set -e
sudo yum update -y
sudo amazon-linux-extras install docker -y
sudo service docker start
sudo chkconfig docker on
sudo usermod -a -G docker $USER
docker info
docker ps -a

sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
docker-compose version

nextcloud in docker: https://blog.ssdnodes.com/blog/installing-nextcloud-docker/
